// AUTOGENERATED FILE. DO NOT EDIT.
package com.myapp.features.marks
import kotlinx.serialization.Serializable
import com.myapp.common.base.*
import com.myapp.common.dtos.*
@Serializable
data class GetMarksParamsDTO(
    val page: Int,
    val limit: Int,
) : DTOParams()
@Serializable
data class MarkDataDTO(
    val id: Int,
    val questionId: Int,
    val isCorrect: Boolean,
    val createdAt: String,
)
