// AUTOGENERATED FILE. DO NOT EDIT.
package com.myapp.features.marks
import com.myapp.common.base.*
import com.myapp.common.dtos.*
data class GetMarksParamsDTO(
    val page: Int,
    val limit: Int,
) : DTOParams()

data class MarkDataDTO(
    val id: Int,
    val questionId: Int,
    val isCorrect: Boolean,
    val createdAt: String,
)

