// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.marks
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*
import io.ktor.server.application.*
import io.ktor.server.routing.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.auth.*

interface MarksService {
    suspend fun GetMarks(body: EmptyRequestDTO, params: GetMarksParamsDTO, userId: Int): DTOResponse<List<MarkDataDTO>>
}

fun Route.marksRoutes(service: MarksService) {
    get("/marks") {
        val body = call.receive<EmptyRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        // Query Binding
        val p_page = call.request.queryParameters["page"]?.toIntOrNull() ?: 1
        val p_limit = call.request.queryParameters["limit"]?.toIntOrNull() ?: 10
        val params = GetMarksParamsDTO(page = p_page, limit = p_limit)
        call.respond(service.GetMarks(body, params, userId))
    }
}
