/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.quizbackend.contracts.features.marks

import com.quizbackend.contracts.common.base.*

interface MarksService {
    suspend fun GetMarks(body: EmptyRequestDTO): DTOResponse<MarkListResponse>
}
