/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.quizbackend.com.quizbackend.contracts.features.marks

import com.quizbackend.com.quizbackend.contracts.common.DTOResponse
import com.quizbackend.com.quizbackend.contracts.common.EmptyRequestDTO
import com.quizbackend.com.quizbackend.contracts.common.MarkListResponse
import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.auth.*
import com.quizbackend.contracts.common.*

interface MarksService {
    suspend fun GetMarks(body: EmptyRequestDTO): ApplicationCall.() -> DTOResponse<MarkListResponse>
}

fun Route.marksRoutes(service: MarksService) {
    route("") {
get("/marks") {
            val response = service.GetMarks(EmptyRequestDTO()).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }
    }
}