/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.example.features.marks

import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.auth.*
import com.example.common.*

fun Route.marksRoutes() {
    route("") {
        get("/marks") {
            // TODO: Implement logic for GetMarks
            // val response: MarkListResponse = service.doSomething(requestBody)
            call.respond(HttpStatusCode.NotImplemented, "Endpoint GetMarks not implemented yet.")
        }
    }
}