// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.marks
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*
import io.ktor.server.application.*
import io.ktor.server.auth.*
import io.ktor.server.routing.*
import io.ktor.server.request.*
import io.ktor.server.response.*

interface MarksService {
    suspend fun GetMarks(body: EmptyRequestDTO, params: GetMarksParamsDTO): DTOResponse<List<MarkDataDTO>>
}

fun Route.marksRoutes(service: MarksService) {
    authenticate("auth-bearer") {
        get("/marks") {
            val body = call.receive<EmptyRequestDTO>()
            // Query Binding
            val p_page = call.request.queryParameters["page"]?.toIntOrNull() ?: throw IllegalArgumentException("Missing page")
            val p_limit = call.request.queryParameters["limit"]?.toIntOrNull() ?: throw IllegalArgumentException("Missing limit")
            val params=GetMarksParamsDTO(page=p_page, limit=p_limit)
            call.respond(service.GetMarks(body, params))
        }
    }
}