/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.quizbackend.contracts.features.communities

import com.quizbackend.contracts.common.base.*

interface CommunitiesService {
    suspend fun SendFriendRequest(body: SendFriendRequestDTO): DTOResponse<FriendRequestResponse>
    suspend fun RespondFriendRequest(body: EmptyRequestDTO): DTOResponse<GenericResponse>
    suspend fun SearchUsers(body: EmptyRequestDTO): DTOResponse<UserListResponse>
}
