/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.quizbackend.com.quizbackend.contracts.features.communities

import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.auth.*
import com.quizbackend.contracts.common.*

interface CommunitiesService {
    suspend fun SendFriendRequest(body: SendFriendRequestDTO): ApplicationCall.() -> DTOResponse<FriendRequestResponse>
    suspend fun AcceptFriendRequest(body: EmptyRequestDTO): ApplicationCall.() -> DTOResponse<FriendRequestResponse>
    suspend fun SearchUsers(body: EmptyRequestDTO): ApplicationCall.() -> DTOResponse<UserListResponse>
}

fun Route.communitiesRoutes(service: CommunitiesService) {
    route("") {
post("/communities/friend-requests") {
            val requestBody = try {
                call.receive<SendFriendRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, DTOResponse<Unit>(false, null, "Serialization Error: ${e.localizedMessage}"))
                return@post
            }
            val response = service.SendFriendRequest(requestBody).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

put("/communities/friend-requests/{id}/accept") {
            val response = service.AcceptFriendRequest(EmptyRequestDTO()).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

get("/communities/users") {
            val response = service.SearchUsers(EmptyRequestDTO()).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }
    }
}