// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.communities
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*
data class SendFriendRequestDTO(
    val targetUserId: Int,
) : DTORequest()

data class FriendRequestDataDTO(
    val id: Int,
    val senderId: Int,
    val receiverId: Int,
    val status: String,
    val createdAt: String,
)

data class AcceptFriendRequestParamsDTO(
    val id: Int,
) : DTOParams()

data class SearchUsersParamsDTO(
    val username: String,
) : DTOParams()

data class PublicUserProfileDTO(
    val id: Int,
    val username: String,
    val name: String,
    val surname: String,
)

