// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.communities
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*
import io.ktor.server.application.*
import io.ktor.server.routing.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.auth.*

interface CommunitiesService {
    suspend fun SendFriendRequest(body: SendFriendRequestDTO, userId: Int): DTOResponse<FriendRequestDataDTO>
    suspend fun AcceptFriendRequest(id: Int, body: EmptyRequestDTO, params: AcceptFriendRequestParamsDTO, userId: Int): DTOResponse<FriendRequestDataDTO>
    suspend fun SearchUsers(body: EmptyRequestDTO, params: SearchUsersParamsDTO, userId: Int): DTOResponse<List<PublicUserProfileDTO>>
}

fun Route.communitiesRoutes(service: CommunitiesService) {
    post("/communities/friend-requests") {
        val body = call.receive<SendFriendRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        call.respond(service.SendFriendRequest(body, userId))
    }
    put("/communities/friend-requests/{id}/accept") {
        val id = call.parameters["id"]?.toInt()!!
        val body = call.receive<EmptyRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        // Query Binding
        val p_id = call.request.queryParameters["id"]?.toIntOrNull() ?: id
        val params = AcceptFriendRequestParamsDTO(id = p_id)
        call.respond(service.AcceptFriendRequest(id, body, params, userId))
    }
    get("/communities/users") {
        val body = call.receive<EmptyRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        // Query Binding
        val p_username = call.request.queryParameters["username"] ?: ""
        val params = SearchUsersParamsDTO(username = p_username)
        call.respond(service.SearchUsers(body, params, userId))
    }
}
