// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.communities
import kotlinx.serialization.Serializable
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*
@Serializable
data class SendFriendRequestDTO(
    val targetUserId: Int,
) : DTORequest()
@Serializable
data class FriendRequestDataDTO(
    val id: Int,
    val senderId: Int,
    val receiverId: Int,
    val status: String,
    val createdAt: String,
)
@Serializable
data class AcceptFriendRequestParamsDTO(
    val id: Int,
) : DTOParams()
@Serializable
data class SearchUsersParamsDTO(
    val username: String,
) : DTOParams()
@Serializable
data class PublicUserProfileDTO(
    val id: Int,
    val username: String,
    val name: String,
    val surname: String,
)
