// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.communities
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*
import io.ktor.server.application.*
import io.ktor.server.auth.*
import io.ktor.server.routing.*
import io.ktor.server.request.*
import io.ktor.server.response.*

interface CommunitiesService {
    suspend fun SendFriendRequest(body: SendFriendRequestDTO): DTOResponse<FriendRequestDataDTO>
    suspend fun AcceptFriendRequest(id: Int, body: EmptyRequestDTO, params: AcceptFriendRequestParamsDTO): DTOResponse<FriendRequestDataDTO>
    suspend fun SearchUsers(body: EmptyRequestDTO, params: SearchUsersParamsDTO): DTOResponse<List<PublicUserProfileDTO>>
}

fun Route.communitiesRoutes(service: CommunitiesService) {
    authenticate("auth-bearer") {
        post("/communities/friend-requests") {
            val body = call.receive<SendFriendRequestDTO>()
            call.respond(service.SendFriendRequest(body))
        }
        put("/communities/friend-requests/{id}/accept") {
            val id = call.parameters["id"]?.toIntOrNull() ?: throw IllegalArgumentException("Invalid id")
            val body = call.receive<EmptyRequestDTO>()
            // Query Binding
            val p_id = call.request.queryParameters["id"]?.toIntOrNull() ?: throw IllegalArgumentException("Missing id")
            val params=AcceptFriendRequestParamsDTO(id=p_id)
            call.respond(service.AcceptFriendRequest(id, body, params))
        }
        get("/communities/users") {
            val body = call.receive<EmptyRequestDTO>()
            // Query Binding
            val p_username = call.request.queryParameters["username"] ?: throw IllegalArgumentException("Missing username")
            val params=SearchUsersParamsDTO(username=p_username)
            call.respond(service.SearchUsers(body, params))
        }
    }
}