/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.quizbackend.contracts.features.auth

import com.quizbackend.contracts.common.base.*

interface AuthService {
    suspend fun Login(body: LoginRequestDTO): DTOResponse<LoginResponseDTO>
    suspend fun Signup(body: SignupRequestDTO): DTOResponse<GenericResponseDTO>
    suspend fun Logout(body: EmptyRequestDTO): DTOResponse<GenericResponseDTO>
    suspend fun DeleteAccount(body: EmptyRequestDTO): DTOResponse<MessageResponseDTO>
    suspend fun RecoverPassword(body: RecoverPasswordRequestDTO): DTOResponse<MessageResponseDTO>
    suspend fun VerifyEmail(body: VerifyEmailRequestDTO): DTOResponse<GenericResponseDTO>
    suspend fun MustChangePassword(body: EmptyRequestDTO): DTOResponse<MustChangePasswordResponseDTO>
    suspend fun ChangePassword(body: ChangePasswordRequestDTO): DTOResponse<GenericResponseDTO>
    suspend fun Status(body: EmptyRequestDTO): DTOResponse<UserStatusResponseDTO>
}
