/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.quizbackend.contracts.features.auth

import com.quizbackend.contracts.common.base.*

interface AuthService {
    suspend fun Login(body: LoginRequestDTO): DTOResponse<LoginResponse>
    suspend fun Signup(body: SignupRequestDTO): DTOResponse<GenericResponse>
    suspend fun Logout(body: EmptyRequestDTO): DTOResponse<GenericResponse>
    suspend fun DeleteAccount(body: EmptyRequestDTO): DTOResponse<MessageResponse>
    suspend fun RecoverPassword(body: RecoverPasswordRequestDTO): DTOResponse<MessageResponse>
    suspend fun VerifyEmail(body: VerifyEmailRequestDTO): DTOResponse<GenericResponse>
    suspend fun MustChangePassword(body: EmptyRequestDTO): DTOResponse<MustChangePasswordResponse>
    suspend fun ChangePassword(body: ChangePasswordRequestDTO): DTOResponse<GenericResponse>
    suspend fun Status(body: EmptyRequestDTO): DTOResponse<UserStatusResponse>
}
