// AUTOGENERATED FILE. DO NOT EDIT.
package com.myapp.features.auth
import com.myapp.common.base.*
import com.myapp.common.dtos.*
import io.ktor.server.application.*
import io.ktor.server.routing.*
import io.ktor.server.request.*
import io.ktor.server.response.*

interface AuthService {
    suspend fun Login(body: LoginRequestDTO): DTOResponse<LoginDataDTO>
    suspend fun Signup(body: SignupRequestDTO): DTOResponse<SignupResponseDTO>
    suspend fun Logout(body: EmptyRequestDTO): DTOResponse<Void>
    suspend fun DeleteAccount(body: EmptyRequestDTO): DTOResponse<MessageDataDTO>
    suspend fun RecoverPassword(body: RecoverPasswordRequestDTO): DTOResponse<MessageDataDTO>
    suspend fun VerifyEmail(body: VerifyEmailRequestDTO): DTOResponse<Void>
    suspend fun MustChangePassword(body: EmptyRequestDTO): DTOResponse<MustChangePasswordDataDTO>
    suspend fun ChangePassword(body: ChangePasswordRequestDTO): DTOResponse<Void>
    suspend fun Status(body: EmptyRequestDTO): DTOResponse<UserStatusDataDTO>
}

fun Route.authRoutes(service: AuthService) {
    post("/auth/login") {
        val body = call.receive<LoginRequestDTO>()
        call.respond(service.Login(body))
    }
    post("/auth/signup") {
        val body = call.receive<SignupRequestDTO>()
        call.respond(service.Signup(body))
    }
    post("/auth/logout") {
        val body = call.receive<EmptyRequestDTO>()
        call.respond(service.Logout(body))
    }
    delete("/auth/account") {
        val body = call.receive<EmptyRequestDTO>()
        call.respond(service.DeleteAccount(body))
    }
    post("/auth/recover") {
        val body = call.receive<RecoverPasswordRequestDTO>()
        call.respond(service.RecoverPassword(body))
    }
    post("/auth/verify") {
        val body = call.receive<VerifyEmailRequestDTO>()
        call.respond(service.VerifyEmail(body))
    }
    get("/auth/must-change-password") {
        val body = call.receive<EmptyRequestDTO>()
        call.respond(service.MustChangePassword(body))
    }
    post("/auth/change-password") {
        val body = call.receive<ChangePasswordRequestDTO>()
        call.respond(service.ChangePassword(body))
    }
    get("/auth/status") {
        val body = call.receive<EmptyRequestDTO>()
        call.respond(service.Status(body))
    }
}