// AUTOGENERATED FILE. DO NOT EDIT.
package com.myapp.features.auth
import com.myapp.common.base.*
import com.myapp.common.dtos.*
data class LoginRequestDTO(
    val email: String,
    val passwordHash: String,
    val uniqueDeviceId: String,
) : DTORequest()

data class LoginDataDTO(
    val bearerToken: String,
)

data class SignupRequestDTO(
    val email: String,
    val username: String,
    val name: String,
    val surname: String,
    val passwordHash: String,
    val uniqueDeviceId: String,
) : DTORequest()

data class SignupResponseDTO(
    val bearerToken: String,
)

class MessageDataDTO

data class RecoverPasswordRequestDTO(
    val email: String,
) : DTORequest()

data class VerifyEmailRequestDTO(
    val code: String,
) : DTORequest()

data class MustChangePasswordDataDTO(
    val must_change_password: Boolean,
)

data class ChangePasswordRequestDTO(
    val oldHash: String,
    val newHash: String,
) : DTORequest()

data class UserStatusDataDTO(
    val isVerified: Boolean,
    val mustChangePassword: Boolean,
)

