/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.example.features.auth

import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.auth.*
import com.example.common.*

fun Route.authRoutes() {
    route("") {
        post("/auth/login") {

            val requestBody = try {
                call.receive<LoginRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, "Serialization Error: ${e.localizedMessage}")
                return@post
            }
            // TODO: Implement logic for Login
            // val response: LoginResponse = service.doSomething(requestBody)
            call.respond(HttpStatusCode.NotImplemented, "Endpoint Login not implemented yet.")
        }

        post("/auth/signup") {

            val requestBody = try {
                call.receive<SignupRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, "Serialization Error: ${e.localizedMessage}")
                return@post
            }
            // TODO: Implement logic for Signup
            // val response: GenericResponse = service.doSomething(requestBody)
            call.respond(HttpStatusCode.NotImplemented, "Endpoint Signup not implemented yet.")
        }

        post("/auth/logout") {
            // TODO: Implement logic for Logout
            // val response: GenericResponse = service.doSomething(requestBody)
            call.respond(HttpStatusCode.NotImplemented, "Endpoint Logout not implemented yet.")
        }

        delete("/auth/account") {
            // TODO: Implement logic for DeleteAccount
            // val response: MessageResponse = service.doSomething(requestBody)
            call.respond(HttpStatusCode.NotImplemented, "Endpoint DeleteAccount not implemented yet.")
        }

        post("/auth/recover") {

            val requestBody = try {
                call.receive<RecoverPasswordRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, "Serialization Error: ${e.localizedMessage}")
                return@post
            }
            // TODO: Implement logic for RecoverPassword
            // val response: MessageResponse = service.doSomething(requestBody)
            call.respond(HttpStatusCode.NotImplemented, "Endpoint RecoverPassword not implemented yet.")
        }

        post("/auth/verify") {

            val requestBody = try {
                call.receive<VerifyEmailRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, "Serialization Error: ${e.localizedMessage}")
                return@post
            }
            // TODO: Implement logic for VerifyEmail
            // val response: GenericResponse = service.doSomething(requestBody)
            call.respond(HttpStatusCode.NotImplemented, "Endpoint VerifyEmail not implemented yet.")
        }

        get("/auth/must-change-password") {
            // TODO: Implement logic for MustChangePassword
            // val response: MustChangePasswordResponse = service.doSomething(requestBody)
            call.respond(HttpStatusCode.NotImplemented, "Endpoint MustChangePassword not implemented yet.")
        }

        post("/auth/change-password") {

            val requestBody = try {
                call.receive<ChangePasswordRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, "Serialization Error: ${e.localizedMessage}")
                return@post
            }
            // TODO: Implement logic for ChangePassword
            // val response: GenericResponse = service.doSomething(requestBody)
            call.respond(HttpStatusCode.NotImplemented, "Endpoint ChangePassword not implemented yet.")
        }

        get("/auth/status") {
            // TODO: Implement logic for Status
            // val response: UserStatusResponse = service.doSomething(requestBody)
            call.respond(HttpStatusCode.NotImplemented, "Endpoint Status not implemented yet.")
        }
    }
}