/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.quizbackend.com.quizbackend.contracts.features.auth

import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.auth.*
import com.quizbackend.contracts.common.*

interface AuthService {
    suspend fun Login(body: LoginRequestDTO): ApplicationCall.() -> DTOResponse<LoginResponse>
    suspend fun Signup(body: SignupRequestDTO): ApplicationCall.() -> DTOResponse<GenericResponse>
    suspend fun Logout(body: EmptyRequestDTO): ApplicationCall.() -> DTOResponse<GenericResponse>
    suspend fun DeleteAccount(body: EmptyRequestDTO): ApplicationCall.() -> DTOResponse<MessageResponse>
    suspend fun RecoverPassword(body: RecoverPasswordRequestDTO): ApplicationCall.() -> DTOResponse<MessageResponse>
    suspend fun VerifyEmail(body: VerifyEmailRequestDTO): ApplicationCall.() -> DTOResponse<GenericResponse>
    suspend fun MustChangePassword(body: EmptyRequestDTO): ApplicationCall.() -> DTOResponse<MustChangePasswordResponse>
    suspend fun ChangePassword(body: ChangePasswordRequestDTO): ApplicationCall.() -> DTOResponse<GenericResponse>
    suspend fun Status(body: EmptyRequestDTO): ApplicationCall.() -> DTOResponse<UserStatusResponse>
}

fun Route.authRoutes(service: AuthService) {
    route("") {
post("/auth/login") {
            val requestBody = try {
                call.receive<LoginRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, DTOResponse<Unit>(false, null, "Serialization Error: ${e.localizedMessage}"))
                return@post
            }
            val response = service.Login(requestBody).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

post("/auth/signup") {
            val requestBody = try {
                call.receive<SignupRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, DTOResponse<Unit>(false, null, "Serialization Error: ${e.localizedMessage}"))
                return@post
            }
            val response = service.Signup(requestBody).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

post("/auth/logout") {
            val response = service.Logout(EmptyRequestDTO()).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

delete("/auth/account") {
            val response = service.DeleteAccount(EmptyRequestDTO()).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

post("/auth/recover") {
            val requestBody = try {
                call.receive<RecoverPasswordRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, DTOResponse<Unit>(false, null, "Serialization Error: ${e.localizedMessage}"))
                return@post
            }
            val response = service.RecoverPassword(requestBody).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

post("/auth/verify") {
            val requestBody = try {
                call.receive<VerifyEmailRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, DTOResponse<Unit>(false, null, "Serialization Error: ${e.localizedMessage}"))
                return@post
            }
            val response = service.VerifyEmail(requestBody).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

get("/auth/must-change-password") {
            val response = service.MustChangePassword(EmptyRequestDTO()).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

post("/auth/change-password") {
            val requestBody = try {
                call.receive<ChangePasswordRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, DTOResponse<Unit>(false, null, "Serialization Error: ${e.localizedMessage}"))
                return@post
            }
            val response = service.ChangePassword(requestBody).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

get("/auth/status") {
            val response = service.Status(EmptyRequestDTO()).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }
    }
}