// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.auth
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*
import io.ktor.server.application.*
import io.ktor.server.routing.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.auth.*

interface AuthService {
    suspend fun Login(body: LoginRequestDTO): DTOResponse<LoginDataDTO>
    suspend fun Signup(body: SignupRequestDTO): DTOResponse<SignupResponseDTO>
    suspend fun Logout(body: EmptyRequestDTO, token: String): DTOResponse<Void>
    suspend fun DeleteAccount(body: EmptyRequestDTO, userId: Int): DTOResponse<MessageDataDTO>
    suspend fun RecoverPassword(body: RecoverPasswordRequestDTO): DTOResponse<MessageDataDTO>
    suspend fun VerifyEmail(body: VerifyEmailRequestDTO): DTOResponse<Void>
    suspend fun MustChangePassword(body: EmptyRequestDTO, userId: Int): DTOResponse<MustChangePasswordDataDTO>
    suspend fun ChangePassword(body: ChangePasswordRequestDTO, userId: Int): DTOResponse<Void>
    suspend fun Status(body: EmptyRequestDTO, userId: Int): DTOResponse<UserStatusDataDTO>
}

fun Route.publicAuthRoutes(service: AuthService) {
    post("/auth/login") {
        val body = call.receive<LoginRequestDTO>()
        call.respond(service.Login(body))
    }
    post("/auth/signup") {
        val body = call.receive<SignupRequestDTO>()
        call.respond(service.Signup(body))
    }
    post("/auth/recover") {
        val body = call.receive<RecoverPasswordRequestDTO>()
        call.respond(service.RecoverPassword(body))
    }
    post("/auth/verify") {
        val body = call.receive<VerifyEmailRequestDTO>()
        call.respond(service.VerifyEmail(body))
    }
}

fun Route.protectedAuthRoutes(service: AuthService) {
    post("/auth/logout") {
        val body = call.receive<EmptyRequestDTO>()
        val token = call.request.headers["Authorization"]?.removePrefix("Bearer ")?.trim() ?: ""
        call.respond(service.Logout(body, token))
    }
    delete("/auth/account") {
        val body = call.receive<EmptyRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        call.respond(service.DeleteAccount(body, userId))
    }
    get("/auth/must-change-password") {
        val body = call.receive<EmptyRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        call.respond(service.MustChangePassword(body, userId))
    }
    post("/auth/change-password") {
        val body = call.receive<ChangePasswordRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        call.respond(service.ChangePassword(body, userId))
    }
    get("/auth/status") {
        val body = call.receive<EmptyRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        call.respond(service.Status(body, userId))
    }
}
