// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.auth
import kotlinx.serialization.Serializable
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*
@Serializable
data class LoginRequestDTO(
    val email: String,
    val passwordHash: String,
    val uniqueDeviceId: String,
) : DTORequest()
@Serializable
data class LoginDataDTO(
    val bearerToken: String,
)
@Serializable
data class SignupRequestDTO(
    val email: String,
    val username: String,
    val name: String,
    val surname: String,
    val passwordHash: String,
    val uniqueDeviceId: String,
) : DTORequest()
@Serializable
data class SignupResponseDTO(
    val bearerToken: String,
)
@Serializable
class MessageDataDTO
@Serializable
data class RecoverPasswordRequestDTO(
    val email: String,
) : DTORequest()
@Serializable
data class VerifyEmailRequestDTO(
    val code: String,
) : DTORequest()
@Serializable
data class MustChangePasswordDataDTO(
    val must_change_password: Boolean,
)
@Serializable
data class ChangePasswordRequestDTO(
    val oldHash: String,
    val newHash: String,
) : DTORequest()
@Serializable
data class UserStatusDataDTO(
    val isVerified: Boolean,
    val mustChangePassword: Boolean,
)
