// AUTOGENERATED FILE. DO NOT EDIT.
package com.myapp.common.base
import com.myapp.common.errors.ErrorDetailsDTO
abstract class DTORequest
abstract class DTOParams
data class DTOResponse<T>(val success: Boolean, val data: T?, val error: ErrorDetailsDTO?)