// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.common.base
import com.quizbackend.contracts.common.errors.ErrorDetailsDTO
abstract class DTORequest
abstract class DTOParams
data class DTOResponse<T>(val success: Boolean, val data: T?, val error: ErrorDetailsDTO?)