/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.quizbackend.com.quizbackend.contracts.common

import kotlinx.serialization.Serializable

@Serializable
data class DTOResponse<T>(
    val success: Boolean,
    val data: T? = null,
    val message: String? = null,
    val error: String? = null
)

@Serializable
class EmptyRequestDTO

@Serializable
data class BaseResponse(
    val success: Boolean? = null,
    val error: String? = null
)

@Serializable
data class LoginResponse(val _empty: Boolean? = true)

@Serializable
data class GenericResponse(val _empty: Boolean? = true)

@Serializable
data class MessageResponse(val _empty: Boolean? = true)

@Serializable
data class MustChangePasswordResponse(val _empty: Boolean? = true)

@Serializable
data class UserStatusResponse(val _empty: Boolean? = true)

@Serializable
data class ProfileDataResponse(val _empty: Boolean? = true)

@Serializable
data class QuestionListResponse(val _empty: Boolean? = true)

@Serializable
data class QuestionDataResponse(val _empty: Boolean? = true)

@Serializable
data class CollectionListResponse(val _empty: Boolean? = true)

@Serializable
data class IdDataResponse(val _empty: Boolean? = true)

@Serializable
data class CollectionDetailResponse(val _empty: Boolean? = true)

@Serializable
data class MarkListResponse(val _empty: Boolean? = true)

@Serializable
data class FriendRequestResponse(val _empty: Boolean? = true)

@Serializable
data class UserListResponse(val _empty: Boolean? = true)

@Serializable
data class LoginRequestDTO(
    val email: String? = null,
    val passwordHash: String? = null,
    val uniqueId: String? = null
)

@Serializable
data class LoginDataDTO(
    val token: String? = null,
    val message: String? = null
)

@Serializable
data class SignupRequestDTO(
    val email: String? = null,
    val username: String? = null,
    val name: String? = null,
    val surname: String? = null,
    val passwordHash: String? = null
)

@Serializable
data class MessageDataDTO(
    val message: String? = null
)

@Serializable
data class RecoverPasswordRequestDTO(
    val email: String? = null
)

@Serializable
data class VerifyEmailRequestDTO(
    val code: String? = null
)

@Serializable
data class MustChangePasswordDataDTO(
    val must_change_password: Boolean? = null
)

@Serializable
data class ChangePasswordRequestDTO(
    val oldHash: String? = null,
    val newHash: String? = null
)

@Serializable
data class UserStatusDataDTO(
    val id: Int? = null,
    val email: String? = null,
    val username: String? = null,
    val isVerified: Boolean? = null,
    val mustChangePassword: Boolean? = null
)

@Serializable
data class RegisterPushTokenRequestDTO(
    val pushToken: String? = null
)

@Serializable
data class ProfileDataDTO(
    val id: Int? = null,
    val email: String? = null,
    val username: String? = null,
    val name: String? = null,
    val surname: String? = null,
    val isVerified: Boolean? = null
)

@Serializable
data class UpdateProfileRequestDTO(
    val name: String? = null,
    val surname: String? = null,
    val username: String? = null
)

@Serializable
data class AnswerDataDTO(
    val id: Int? = null,
    val text: String? = null,
    val isCorrect: Boolean? = null
)

@Serializable
data class QuestionDataDTO(
    val id: Int? = null,
    val text: String? = null,
    val answers: List<AnswerDataDTO>? = null
)

@Serializable
data class LocalizationDTO(
    val locale: String? = null,
    val text: String? = null
)

@Serializable
data class CreateAnswerInputDTO(
    val localizations: List<LocalizationDTO>? = null
)

@Serializable
data class CreateQuestionInputDTO(
    val localizations: List<LocalizationDTO>? = null,
    val answers: List<CreateAnswerInputDTO>? = null,
    val correctAnswersIndices: List<Int>? = null,
    val isDiscoverable: Boolean? = null,
    val collectionIds: List<Int>? = null
)

@Serializable
data class CreateQuestionsRequestDTO(
    val questions: List<CreateQuestionInputDTO>? = null
)

@Serializable
data class UpdateAnswerInputDTO(
    val id: Int? = null,
    val localizations: List<LocalizationDTO>? = null
)

@Serializable
data class UpdateQuestionRequestDTO(
    val localizations: List<LocalizationDTO>? = null,
    val answers: List<UpdateAnswerInputDTO>? = null,
    val correctAnswersIndices: List<Int>? = null,
    val isDiscoverable: Boolean? = null,
    val collectionIds: List<Int>? = null
)

@Serializable
data class CollectionDataDTO(
    val id: Int? = null,
    val name: String? = null,
    val description: String? = null,
    val isPublic: Boolean? = null,
    val creatorId: Int? = null,
    val createdAt: String? = null
)

@Serializable
data class CollectionDetailDataDTO(
    val id: Int? = null,
    val name: String? = null,
    val description: String? = null,
    val isPublic: Boolean? = null,
    val creatorId: Int? = null,
    val createdAt: String? = null,
    val questionIds: List<Int>? = null
)

@Serializable
data class CreateCollectionRequestDTO(
    val name: String? = null,
    val description: String? = null,
    val isPublic: Boolean? = null
)

@Serializable
data class IdDataDTO(
    val id: Int? = null
)

@Serializable
data class UpdateCollectionRequestDTO(
    val name: String? = null,
    val description: String? = null,
    val isPublic: Boolean? = null
)

@Serializable
data class MarkDataDTO(
    val id: Int? = null,
    val questionId: Int? = null,
    val isCorrect: Boolean? = null,
    val createdAt: String? = null
)

@Serializable
data class SendFriendRequestDTO(
    val targetUserId: Int? = null
)

@Serializable
data class FriendRequestDataDTO(
    val id: Int? = null,
    val senderId: Int? = null,
    val receiverId: Int? = null,
    val status: String? = null,
    val createdAt: String? = null
)

@Serializable
data class PublicUserProfileDTO(
    val id: Int? = null,
    val username: String? = null,
    val name: String? = null,
    val surname: String? = null
)

@Serializable
enum class ErrorType {
    INVALID_CREDENTIALS,
    ACCOUNT_ALREADY_EXISTS,
    EMAIL_NOT_VERIFIED,
    INVALID_VERIFICATION_CODE,
    PASSWORD_TOO_SHORT,
    PASSWORD_REQUIRES_NUMBER,
    PASSWORD_REQUIRES_UPPERCASE,
    PASSWORD_RECENTLY_USED,
    INVALID_EMAIL_FORMAT,
    TOKEN_EXPIRED,
    INVALID_TOKEN,
    UNAUTHORIZED,
    FORBIDDEN,
    USER_NOT_FOUND,
    USERNAME_ALREADY_TAKEN,
    INVALID_PROFILE_DATA,
    QUESTION_NOT_FOUND,
    INVALID_QUESTION_DATA,
    EMPTY_QUESTION_TEXT,
    MISSING_CORRECT_ANSWER,
    TOO_MANY_ANSWERS,
    COLLECTION_NOT_FOUND,
    COLLECTION_ALREADY_EXISTS,
    CANNOT_MODIFY_PUBLIC_COLLECTION,
    ACCESS_DENIED_TO_COLLECTION,
    FRIEND_REQUEST_ALREADY_SENT,
    FRIEND_REQUEST_NOT_FOUND,
    CANNOT_FRIEND_SELF,
    USER_BLOCKED,
    INTERNAL_SERVER_ERROR,
    BAD_REQUEST,
    METHOD_NOT_ALLOWED,
    NOT_IMPLEMENTED
}

@Serializable
data class ErrorDetailsDTO(
    val type: ErrorType? = null,
    val message: String? = null
)