// AUTOGENERATED FILE. DO NOT EDIT.
package com.myapp.common.dtos
import kotlinx.serialization.Serializable
import com.myapp.common.base.*
@Serializable
class EmptyParamsDTO : DTOParams()
@Serializable
class EmptyRequestDTO : DTORequest()
