// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.common.dtos
import com.quizbackend.contracts.common.base.*
class EmptyParamsDTO : DTOParams()

class EmptyRequestDTO : DTORequest()

