// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.common.dtos
import kotlinx.serialization.Serializable
import com.quizbackend.contracts.common.base.*
@Serializable
class EmptyParamsDTO : DTOParams()
@Serializable
class EmptyRequestDTO : DTORequest()
