// AUTOGENERATED FILE. DO NOT EDIT.
package com.myapp.features.questions
import kotlinx.serialization.Serializable
import com.myapp.common.base.*
import com.myapp.common.dtos.*
@Serializable
data class SearchQuestionsParamsDTO(
    val search: String,
    val page: Int,
    val locale: String,
) : DTOParams()
@Serializable
data class QuestionDataDTO(
    val id: Int,
    val text: String,
    val answers: List<AnswerData>,
)
@Serializable
data class GetQuestionParamsDTO(
    val id: Int,
) : DTOParams()
@Serializable
data class GetQuestionsBatchParamsDTO(
    val ids: List<Int>,
) : DTOParams()
@Serializable
data class CreateQuestionsRequestDTO(
    val questions: List<CreateQuestionInput>,
) : DTORequest()
@Serializable
data class UpdateQuestionRequestDTO(
    val localizations: List<Localization>,
    val answers: List<UpdateAnswerInput>,
    val correctAnswersIndices: List<Int>,
    val isDiscoverable: Boolean,
    val collectionIds: List<Int>,
) : DTORequest()
@Serializable
data class UpdateQuestionParamsDTO(
    val id: Int,
) : DTOParams()
@Serializable
data class DeleteQuestionParamsDTO(
    val id: Int,
) : DTOParams()
