// AUTOGENERATED FILE. DO NOT EDIT.
package com.myapp.features.questions
import com.myapp.common.base.*
import com.myapp.common.dtos.*
data class SearchQuestionsParamsDTO(
    val search: String,
    val page: Int,
    val locale: String,
) : DTOParams()

data class QuestionDataDTO(
    val id: Int,
    val text: String,
    val answers: List<AnswerData>,
)

data class GetQuestionParamsDTO(
    val id: Int,
) : DTOParams()

data class GetQuestionsBatchParamsDTO(
    val ids: List<Int>,
) : DTOParams()

data class CreateQuestionsRequestDTO(
    val questions: List<CreateQuestionInput>,
) : DTORequest()

data class UpdateQuestionRequestDTO(
    val localizations: List<Localization>,
    val answers: List<UpdateAnswerInput>,
    val correctAnswersIndices: List<Int>,
    val isDiscoverable: Boolean,
    val collectionIds: List<Int>,
) : DTORequest()

data class UpdateQuestionParamsDTO(
    val id: Int,
) : DTOParams()

data class DeleteQuestionParamsDTO(
    val id: Int,
) : DTOParams()

