// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.questions
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*

data class SearchQuestionsParamsDTO(
    val search: String,
    val page: Int,
    val locale: String,
) : DTOParams()

data class AnswerData(val id: Int, val text: String)

data class QuestionDataDTO(
    val id: Int,
    val text: String,
    val answers: List<AnswerData>,
)

data class GetQuestionParamsDTO(
    val id: Int,
) : DTOParams()

data class GetQuestionsBatchParamsDTO(
    val ids: String, // Changed to String as it comes from query param
) : DTOParams()

data class CreateQuestionInput(
    val text: String,
    val answers: List<String>,
    val correctAnswers: List<Int>,
    val collectionId: Int?,
    val isDiscoverable: Boolean
)

data class CreateQuestionsRequestDTO(
    val questions: List<CreateQuestionInput>,
) : DTORequest()

data class Localization(val locale: String, val text: String)
data class UpdateAnswerInput(val id: Int?, val text: String)

data class UpdateQuestionRequestDTO(
    val localizations: List<Localization>,
    val answers: List<UpdateAnswerInput>,
    val correctAnswersIndices: List<Int>,
    val isDiscoverable: Boolean,
    val collectionIds: List<Int>,
) : DTORequest()

data class UpdateQuestionParamsDTO(
    val id: Int,
) : DTOParams()

data class DeleteQuestionParamsDTO(
    val id: Int,
) : DTOParams()
