/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.quizbackend.contracts.features.questions

import com.quizbackend.contracts.common.base.*

interface QuestionsService {
    suspend fun DiscoverQuestions(body: EmptyRequestDTO, params: SearchQuestionsParamsDTO): DTOResponse<QuestionListResponse>
    suspend fun GetQuestion(body: EmptyRequestDTO, params: GetQuestionParamsDTO): DTOResponse<QuestionDataResponse>
    suspend fun GetQuestionsBatch(body: EmptyRequestDTO, params: GetQuestionsBatchParamsDTO): DTOResponse<QuestionListResponse>
    suspend fun CreateQuestions(body: CreateQuestionsRequestDTO): DTOResponse<GenericResponse>
    suspend fun UpdateQuestion(body: UpdateQuestionRequestDTO, params: UpdateQuestionParamsDTO): DTOResponse<QuestionDataResponse>
    suspend fun DeleteQuestion(body: EmptyRequestDTO, params: DeleteQuestionParamsDTO): DTOResponse<GenericResponse>
}
