/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.quizbackend.com.quizbackend.contracts.features.questions

import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.auth.*
import com.quizbackend.contracts.common.*

interface QuestionsService {
    suspend fun DiscoverQuestions(body: EmptyRequestDTO): ApplicationCall.() -> DTOResponse<QuestionListResponse>
    suspend fun CreateQuestions(body: CreateQuestionsRequestDTO): ApplicationCall.() -> DTOResponse<GenericResponse>
    suspend fun GetQuestion(body: EmptyRequestDTO): ApplicationCall.() -> DTOResponse<QuestionDataResponse>
    suspend fun UpdateQuestion(body: UpdateQuestionRequestDTO): ApplicationCall.() -> DTOResponse<QuestionDataResponse>
    suspend fun DeleteQuestion(body: EmptyRequestDTO): ApplicationCall.() -> DTOResponse<GenericResponse>
    suspend fun GetQuestionsBatch(body: EmptyRequestDTO): ApplicationCall.() -> DTOResponse<QuestionListResponse>
}

fun Route.questionsRoutes(service: QuestionsService) {
    route("") {
get("/questions") {
            val response = service.DiscoverQuestions(EmptyRequestDTO()).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

post("/questions") {
            val requestBody = try {
                call.receive<CreateQuestionsRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, DTOResponse<Unit>(false, null, "Serialization Error: ${e.localizedMessage}"))
                return@post
            }
            val response = service.CreateQuestions(requestBody).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

get("/questions/{id}") {
            val response = service.GetQuestion(EmptyRequestDTO()).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

put("/questions/{id}") {
            val requestBody = try {
                call.receive<UpdateQuestionRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, DTOResponse<Unit>(false, null, "Serialization Error: ${e.localizedMessage}"))
                return@put
            }
            val response = service.UpdateQuestion(requestBody).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

delete("/questions/{id}") {
            val response = service.DeleteQuestion(EmptyRequestDTO()).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

get("/questions/batch") {
            val response = service.GetQuestionsBatch(EmptyRequestDTO()).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }
    }
}