// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.questions
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*
import io.ktor.server.application.*
import io.ktor.server.routing.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.auth.*

interface QuestionsService {
    suspend fun DiscoverQuestions(body: EmptyRequestDTO, params: SearchQuestionsParamsDTO, userId: Int): DTOResponse<List<QuestionDataDTO>>
    suspend fun GetQuestion(id: Int, body: EmptyRequestDTO, params: GetQuestionParamsDTO, userId: Int): DTOResponse<QuestionDataDTO>
    suspend fun GetQuestionsBatch(body: EmptyRequestDTO, params: GetQuestionsBatchParamsDTO, userId: Int): DTOResponse<List<QuestionDataDTO>>
    suspend fun CreateQuestions(body: CreateQuestionsRequestDTO, userId: Int): DTOResponse<Void>
    suspend fun UpdateQuestion(id: Int, body: UpdateQuestionRequestDTO, params: UpdateQuestionParamsDTO, userId: Int): DTOResponse<QuestionDataDTO>
    suspend fun DeleteQuestion(id: Int, body: EmptyRequestDTO, params: DeleteQuestionParamsDTO, userId: Int): DTOResponse<Void>
}

fun Route.questionsRoutes(service: QuestionsService) {
    get("/questions") {
        val body = call.receive<EmptyRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        // Query Binding
        val p_search = call.request.queryParameters["search"] ?: ""
        val p_page = call.request.queryParameters["page"]?.toIntOrNull() ?: 1
        val p_locale = call.request.queryParameters["locale"] ?: "en"
        val params = SearchQuestionsParamsDTO(search = p_search, page = p_page, locale = p_locale)
        call.respond(service.DiscoverQuestions(body, params, userId))
    }
    get("/questions/{id}") {
        val id = call.parameters["id"]?.toInt()!!
        val body = call.receive<EmptyRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        // Query Binding
        val p_id = call.request.queryParameters["id"]?.toIntOrNull() ?: id // Use path param if query missing
        val params = GetQuestionParamsDTO(id = p_id)
        call.respond(service.GetQuestion(id, body, params, userId))
    }
    get("/questions/batch") {
        val body = call.receive<EmptyRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        // Query Binding
        val p_ids = call.request.queryParameters["ids"] ?: ""
        val params = GetQuestionsBatchParamsDTO(ids = p_ids)
        call.respond(service.GetQuestionsBatch(body, params, userId))
    }
    post("/questions") {
        val body = call.receive<CreateQuestionsRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        call.respond(service.CreateQuestions(body, userId))
    }
    put("/questions/{id}") {
        val id = call.parameters["id"]?.toInt()!!
        val body = call.receive<UpdateQuestionRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        // Query Binding
        val p_id = call.request.queryParameters["id"]?.toIntOrNull() ?: id
        val params = UpdateQuestionParamsDTO(id = p_id)
        call.respond(service.UpdateQuestion(id, body, params, userId))
    }
    delete("/questions/{id}") {
        val id = call.parameters["id"]?.toInt()!!
        val body = call.receive<EmptyRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        // Query Binding
        val p_id = call.request.queryParameters["id"]?.toIntOrNull() ?: id
        val params = DeleteQuestionParamsDTO(id = p_id)
        call.respond(service.DeleteQuestion(id, body, params, userId))
    }
}
