// AUTOGENERATED FILE. DO NOT EDIT.
package com.myapp.features.questions
import com.myapp.common.base.*
import com.myapp.common.dtos.*
import io.ktor.server.application.*
import io.ktor.server.auth.*
import io.ktor.server.routing.*
import io.ktor.server.request.*
import io.ktor.server.response.*

interface QuestionsService {
    suspend fun DiscoverQuestions(body: EmptyRequestDTO, params: SearchQuestionsParamsDTO): DTOResponse<List<QuestionDataDTO>>
    suspend fun GetQuestion(id: Int, body: EmptyRequestDTO, params: GetQuestionParamsDTO): DTOResponse<QuestionDataDTO>
    suspend fun GetQuestionsBatch(body: EmptyRequestDTO, params: GetQuestionsBatchParamsDTO): DTOResponse<List<QuestionDataDTO>>
    suspend fun CreateQuestions(body: CreateQuestionsRequestDTO): DTOResponse<Unit>
    suspend fun UpdateQuestion(id: Int, body: UpdateQuestionRequestDTO, params: UpdateQuestionParamsDTO): DTOResponse<QuestionDataDTO>
    suspend fun DeleteQuestion(id: Int, body: EmptyRequestDTO, params: DeleteQuestionParamsDTO): DTOResponse<Unit>
}

fun Route.questionsRoutes(service: QuestionsService) {
    authenticate("auth-bearer") {
        get("/questions") {
            val body = call.receive<EmptyRequestDTO>()
            // Query Binding
            val p_search = call.request.queryParameters["search"] ?: throw IllegalArgumentException("Missing search")
            val p_page = call.request.queryParameters["page"].toIntOrNull() ?: throw IllegalArgumentException("Missing page")
            val p_locale = call.request.queryParameters["locale"] ?: throw IllegalArgumentException("Missing locale")
            val params=SearchQuestionsParamsDTO(search=p_search, page=p_page, locale=p_locale)
            call.respond(service.DiscoverQuestions(body, params))
        }
        get("/questions/{id}") {
            val id = call.parameters["id"]?.toIntOrNull() ?: throw IllegalArgumentException("Invalid id")
            val body = call.receive<EmptyRequestDTO>()
            // Query Binding
            val p_id = call.request.queryParameters["id"].toIntOrNull() ?: throw IllegalArgumentException("Missing id")
            val params=GetQuestionParamsDTO(id=p_id)
            call.respond(service.GetQuestion(id, body, params))
        }
        get("/questions/batch") {
            val body = call.receive<EmptyRequestDTO>()
            // Query Binding
            val p_ids = call.request.queryParameters["ids"] ?: throw IllegalArgumentException("Missing ids")
            val params=GetQuestionsBatchParamsDTO(ids=p_ids)
            call.respond(service.GetQuestionsBatch(body, params))
        }
        post("/questions") {
            val body = call.receive<CreateQuestionsRequestDTO>()
            call.respond(service.CreateQuestions(body))
        }
        put("/questions/{id}") {
            val id = call.parameters["id"]?.toIntOrNull() ?: throw IllegalArgumentException("Invalid id")
            val body = call.receive<UpdateQuestionRequestDTO>()
            // Query Binding
            val p_id = call.request.queryParameters["id"].toIntOrNull() ?: throw IllegalArgumentException("Missing id")
            val params=UpdateQuestionParamsDTO(id=p_id)
            call.respond(service.UpdateQuestion(id, body, params))
        }
        delete("/questions/{id}") {
            val id = call.parameters["id"]?.toIntOrNull() ?: throw IllegalArgumentException("Invalid id")
            val body = call.receive<EmptyRequestDTO>()
            // Query Binding
            val p_id = call.request.queryParameters["id"].toIntOrNull() ?: throw IllegalArgumentException("Missing id")
            val params=DeleteQuestionParamsDTO(id=p_id)
            call.respond(service.DeleteQuestion(id, body, params))
        }
    }
}