/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.quizbackend.com.quizbackend.contracts.features.collections

import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.auth.*
import com.quizbackend.contracts.common.*

interface CollectionsService {
    suspend fun GetCollectionsList(body: EmptyRequestDTO): ApplicationCall.() -> DTOResponse<CollectionListResponse>
    suspend fun CreateCollection(body: CreateCollectionRequestDTO): ApplicationCall.() -> DTOResponse<IdDataResponse>
    suspend fun GetCollection(body: EmptyRequestDTO): ApplicationCall.() -> DTOResponse<CollectionDetailResponse>
    suspend fun UpdateCollection(body: UpdateCollectionRequestDTO): ApplicationCall.() -> DTOResponse<GenericResponse>
}

fun Route.collectionsRoutes(service: CollectionsService) {
    route("") {
get("/collections") {
            val response = service.GetCollectionsList(EmptyRequestDTO()).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

post("/collections") {
            val requestBody = try {
                call.receive<CreateCollectionRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, DTOResponse<Unit>(false, null, "Serialization Error: ${e.localizedMessage}"))
                return@post
            }
            val response = service.CreateCollection(requestBody).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

get("/collections/{id}") {
            val response = service.GetCollection(EmptyRequestDTO()).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

put("/collections/{id}") {
            val requestBody = try {
                call.receive<UpdateCollectionRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, DTOResponse<Unit>(false, null, "Serialization Error: ${e.localizedMessage}"))
                return@put
            }
            val response = service.UpdateCollection(requestBody).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }
    }
}