// AUTOGENERATED FILE. DO NOT EDIT.
package com.myapp.features.collections
import com.myapp.common.base.*
import com.myapp.common.dtos.*
data class ListCollectionsParamsDTO(
    val name: String,
) : DTOParams()

data class CollectionDataDTO(
    val id: Int,
    val name: String,
    val description: String,
    val isPublic: Boolean,
    val creatorId: Int,
    val createdAt: String,
)

data class GetCollectionParamsDTO(
    val id: Int,
) : DTOParams()

data class CollectionDetailDataDTO(
    val id: Int,
    val name: String,
    val description: String,
    val isPublic: Boolean,
    val creatorId: Int,
    val createdAt: String,
    val questionIds: List<Int>,
)

data class CreateCollectionRequestDTO(
    val name: String,
    val description: String,
    val isPublic: Boolean,
) : DTORequest()

data class IdDataDTO(
    val id: Int,
)

data class UpdateCollectionRequestDTO(
    val name: String,
    val description: String,
    val isPublic: Boolean,
) : DTORequest()

data class UpdateCollectionParamsDTO(
    val id: Int,
) : DTOParams()

