/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.example.features.collections

import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.auth.*
import com.example.common.*

fun Route.collectionsRoutes() {
    route("") {
        get("/collections") {
            // TODO: Implement logic for GetCollectionsList
            // val response: CollectionListResponse = service.doSomething(requestBody)
            call.respond(HttpStatusCode.NotImplemented, "Endpoint GetCollectionsList not implemented yet.")
        }

        post("/collections") {

            val requestBody = try {
                call.receive<CreateCollectionRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, "Serialization Error: ${e.localizedMessage}")
                return@post
            }
            // TODO: Implement logic for CreateCollection
            // val response: IdDataResponse = service.doSomething(requestBody)
            call.respond(HttpStatusCode.NotImplemented, "Endpoint CreateCollection not implemented yet.")
        }

        get("/collections/{id}") {
            // TODO: Implement logic for GetCollection
            // val response: CollectionDetailResponse = service.doSomething(requestBody)
            call.respond(HttpStatusCode.NotImplemented, "Endpoint GetCollection not implemented yet.")
        }

        put("/collections/{id}") {

            val requestBody = try {
                call.receive<UpdateCollectionRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, "Serialization Error: ${e.localizedMessage}")
                return@put
            }
            // TODO: Implement logic for UpdateCollection
            // val response: GenericResponse = service.doSomething(requestBody)
            call.respond(HttpStatusCode.NotImplemented, "Endpoint UpdateCollection not implemented yet.")
        }
    }
}