/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.quizbackend.contracts.features.collections

import com.quizbackend.contracts.common.base.*

interface CollectionsService {
    suspend fun GetCollectionsList(body: EmptyRequestDTO): DTOResponse<CollectionListResponseDTO>
    suspend fun CreateCollection(body: CreateCollectionRequestDTO): DTOResponse<IdDataResponseDTO>
    suspend fun GetCollection(body: EmptyRequestDTO, params: UpdateCollectionParamsDTO): DTOResponse<CollectionDetailResponseDTO>
    suspend fun UpdateCollection(body: UpdateCollectionRequestDTO, params: UpdateCollectionParamsDTO): DTOResponse<GenericResponseDTO>
    suspend fun DeleteCollection(body: EmptyRequestDTO, params: UpdateCollectionParamsDTO): DTOResponse<GenericResponseDTO>
}
