// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.collections
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*
import io.ktor.server.application.*
import io.ktor.server.routing.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.auth.*

interface CollectionsService {
    suspend fun GetCollectionsList(body: EmptyRequestDTO, params: ListCollectionsParamsDTO, userId: Int): DTOResponse<List<CollectionDataDTO>>
    suspend fun GetCollection(id: Int, body: EmptyRequestDTO, params: GetCollectionParamsDTO, userId: Int): DTOResponse<CollectionDetailDataDTO>
    suspend fun CreateCollection(body: CreateCollectionRequestDTO, userId: Int): DTOResponse<IdDataDTO>
    suspend fun UpdateCollection(id: Int, body: UpdateCollectionRequestDTO, params: UpdateCollectionParamsDTO, userId: Int): DTOResponse<Void>
}

fun Route.collectionsRoutes(service: CollectionsService) {
    get("/collections") {
        val body = call.receive<EmptyRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        // Query Binding
        val p_name = call.request.queryParameters["name"] ?: ""
        val params = ListCollectionsParamsDTO(name = p_name)
        call.respond(service.GetCollectionsList(body, params, userId))
    }
    get("/collections/{id}") {
        val id = call.parameters["id"]?.toInt()!!
        val body = call.receive<EmptyRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        // Query Binding
        val p_id = call.request.queryParameters["id"]?.toIntOrNull() ?: id
        val params = GetCollectionParamsDTO(id = p_id)
        call.respond(service.GetCollection(id, body, params, userId))
    }
    post("/collections") {
        val body = call.receive<CreateCollectionRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        call.respond(service.CreateCollection(body, userId))
    }
    put("/collections/{id}") {
        val id = call.parameters["id"]?.toInt()!!
        val body = call.receive<UpdateCollectionRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        // Query Binding
        val p_id = call.request.queryParameters["id"]?.toIntOrNull() ?: id
        val params = UpdateCollectionParamsDTO(id = p_id)
        call.respond(service.UpdateCollection(id, body, params, userId))
    }
}
