// AUTOGENERATED FILE. DO NOT EDIT.
package com.myapp.features.collections
import kotlinx.serialization.Serializable
import com.myapp.common.base.*
import com.myapp.common.dtos.*
@Serializable
data class ListCollectionsParamsDTO(
    val name: String,
) : DTOParams()
@Serializable
data class CollectionDataDTO(
    val id: Int,
    val name: String,
    val description: String,
    val isPublic: Boolean,
    val creatorId: Int,
    val createdAt: String,
)
@Serializable
data class GetCollectionParamsDTO(
    val id: Int,
) : DTOParams()
@Serializable
data class CollectionDetailDataDTO(
    val id: Int,
    val name: String,
    val description: String,
    val isPublic: Boolean,
    val creatorId: Int,
    val createdAt: String,
    val questionIds: List<Int>,
)
@Serializable
data class CreateCollectionRequestDTO(
    val name: String,
    val description: String,
    val isPublic: Boolean,
) : DTORequest()
@Serializable
data class IdDataDTO(
    val id: Int,
)
@Serializable
data class UpdateCollectionRequestDTO(
    val name: String,
    val description: String,
    val isPublic: Boolean,
) : DTORequest()
@Serializable
data class UpdateCollectionParamsDTO(
    val id: Int,
) : DTOParams()
