// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.collections
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*
import io.ktor.server.application.*
import io.ktor.server.auth.*
import io.ktor.server.routing.*
import io.ktor.server.request.*
import io.ktor.server.response.*

interface CollectionsService {
    suspend fun GetCollectionsList(body: EmptyRequestDTO, params: ListCollectionsParamsDTO): DTOResponse<List<CollectionDataDTO>>
    suspend fun GetCollection(id: Int, body: EmptyRequestDTO, params: GetCollectionParamsDTO): DTOResponse<CollectionDetailDataDTO>
    suspend fun CreateCollection(body: CreateCollectionRequestDTO): DTOResponse<IdDataDTO>
    suspend fun UpdateCollection(id: Int, body: UpdateCollectionRequestDTO, params: UpdateCollectionParamsDTO): DTOResponse<Unit>
}

fun Route.collectionsRoutes(service: CollectionsService) {
    authenticate("auth-bearer") {
        get("/collections") {
            val body = call.receive<EmptyRequestDTO>()
            // Query Binding
            val p_name = call.request.queryParameters["name"] ?: throw IllegalArgumentException("Missing name")
            val params=ListCollectionsParamsDTO(name=p_name)
            call.respond(service.GetCollectionsList(body, params))
        }
        get("/collections/{id}") {
            val id = call.parameters["id"]?.toIntOrNull() ?: throw IllegalArgumentException("Invalid id")
            val body = call.receive<EmptyRequestDTO>()
            // Query Binding
            val p_id = call.request.queryParameters["id"]?.toIntOrNull() ?: throw IllegalArgumentException("Missing id")
            val params=GetCollectionParamsDTO(id=p_id)
            call.respond(service.GetCollection(id, body, params))
        }
        post("/collections") {
            val body = call.receive<CreateCollectionRequestDTO>()
            call.respond(service.CreateCollection(body))
        }
        put("/collections/{id}") {
            val id = call.parameters["id"]?.toIntOrNull() ?: throw IllegalArgumentException("Invalid id")
            val body = call.receive<UpdateCollectionRequestDTO>()
            // Query Binding
            val p_id = call.request.queryParameters["id"]?.toIntOrNull() ?: throw IllegalArgumentException("Missing id")
            val params=UpdateCollectionParamsDTO(id=p_id)
            call.respond(service.UpdateCollection(id, body, params))
        }
    }
}