// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.profile
import kotlinx.serialization.Serializable
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*
@Serializable
data class ProfileDataDTO(
    val id: Int,
    val email: String,
    val username: String,
    val name: String,
    val surname: String,
)
@Serializable
data class UpdateProfileRequestDTO(
    val name: String,
    val surname: String,
    val username: String,
) : DTORequest()
