/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.example.features.profile

import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.auth.*
import com.example.common.*

fun Route.profileRoutes() {
    route("") {
        get("/profile") {
            // TODO: Implement logic for SeeProfile
            // val response: ProfileDataResponse = service.doSomething(requestBody)
            call.respond(HttpStatusCode.NotImplemented, "Endpoint SeeProfile not implemented yet.")
        }

        put("/profile") {

            val requestBody = try {
                call.receive<UpdateProfileRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, "Serialization Error: ${e.localizedMessage}")
                return@put
            }
            // TODO: Implement logic for UpdateProfile
            // val response: ProfileDataResponse = service.doSomething(requestBody)
            call.respond(HttpStatusCode.NotImplemented, "Endpoint UpdateProfile not implemented yet.")
        }
    }
}