// AUTOGENERATED FILE. DO NOT EDIT.
package com.myapp.features.profile
import com.myapp.common.base.*
import com.myapp.common.dtos.*
data class ProfileDataDTO(
    val id: Int,
    val email: String,
    val username: String,
    val name: String,
    val surname: String,
)

data class UpdateProfileRequestDTO(
    val name: String,
    val surname: String,
    val username: String,
) : DTORequest()

