// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.profile
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*
import io.ktor.server.application.*
import io.ktor.server.routing.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.auth.*

interface ProfileService {
    suspend fun SeeProfile(body: EmptyRequestDTO, userId: Int): DTOResponse<ProfileDataDTO>
    suspend fun UpdateProfile(body: UpdateProfileRequestDTO, userId: Int): DTOResponse<ProfileDataDTO>
}

fun Route.profileRoutes(service: ProfileService) {
    get("/profile") {
        val body = call.receive<EmptyRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        call.respond(service.SeeProfile(body, userId))
    }
    put("/profile") {
        val body = call.receive<UpdateProfileRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        call.respond(service.UpdateProfile(body, userId))
    }
}
