/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.quizbackend.contracts.features.profile

import com.quizbackend.contracts.common.base.*

interface ProfileService {
    suspend fun SeeProfile(body: EmptyRequestDTO): DTOResponse<ProfileDataResponseDTO>
    suspend fun UpdateProfile(body: UpdateProfileRequestDTO): DTOResponse<ProfileDataResponseDTO>
}
