/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.quizbackend.com.quizbackend.contracts.features.profile

import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.auth.*
import com.quizbackend.contracts.common.*

interface ProfileService {
    suspend fun SeeProfile(body: EmptyRequestDTO): ApplicationCall.() -> DTOResponse<ProfileDataResponse>
    suspend fun UpdateProfile(body: UpdateProfileRequestDTO): ApplicationCall.() -> DTOResponse<ProfileDataResponse>
}

fun Route.profileRoutes(service: ProfileService) {
    route("") {
get("/profile") {
            val response = service.SeeProfile(EmptyRequestDTO()).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

put("/profile") {
            val requestBody = try {
                call.receive<UpdateProfileRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, DTOResponse<Unit>(false, null, "Serialization Error: ${e.localizedMessage}"))
                return@put
            }
            val response = service.UpdateProfile(requestBody).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }
    }
}