// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.profile
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*
import io.ktor.server.application.*
import io.ktor.server.auth.*
import io.ktor.server.routing.*
import io.ktor.server.request.*
import io.ktor.server.response.*

interface ProfileService {
    suspend fun SeeProfile(body: EmptyRequestDTO): DTOResponse<ProfileDataDTO>
    suspend fun UpdateProfile(body: UpdateProfileRequestDTO): DTOResponse<ProfileDataDTO>
}

fun Route.profileRoutes(service: ProfileService) {
    authenticate("auth-bearer") {
        get("/profile") {
            val body = call.receive<EmptyRequestDTO>()
            call.respond(service.SeeProfile(body))
        }
        put("/profile") {
            val body = call.receive<UpdateProfileRequestDTO>()
            call.respond(service.UpdateProfile(body))
        }
    }
}