// AUTOGENERATED FILE. DO NOT EDIT.
package com.myapp.features.notifications
import kotlinx.serialization.Serializable
import com.myapp.common.base.*
import com.myapp.common.dtos.*
@Serializable
data class RegisterPushTokenRequestDTO(
    val pushToken: String,
) : DTORequest()
