// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.notifications
import kotlinx.serialization.Serializable
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*
@Serializable
data class RegisterPushTokenRequestDTO(
    val pushToken: String,
) : DTORequest()
