/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.quizbackend.com.quizbackend.contracts.features.notifications

import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.auth.*
import com.quizbackend.contracts.common.*

interface NotificationsService {
    suspend fun RegisterPushToken(body: RegisterPushTokenRequestDTO): ApplicationCall.() -> DTOResponse<GenericResponse>
    suspend fun UnregisterPushToken(body: EmptyRequestDTO): ApplicationCall.() -> DTOResponse<GenericResponse>
}

fun Route.notificationsRoutes(service: NotificationsService) {
    route("") {
post("/devices/push-token") {
            val requestBody = try {
                call.receive<RegisterPushTokenRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, DTOResponse<Unit>(false, null, "Serialization Error: ${e.localizedMessage}"))
                return@post
            }
            val response = service.RegisterPushToken(requestBody).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }

delete("/devices/push-token") {
            val response = service.UnregisterPushToken(EmptyRequestDTO()).invoke(call)
            if (response.success) {
                call.respond(HttpStatusCode.OK, response)
            } else {
                call.respond(HttpStatusCode.BadRequest, response)
            }
        }
    }
}