// AUTOGENERATED FILE. DO NOT EDIT.
package com.myapp.features.notifications
import com.myapp.common.base.*
import com.myapp.common.dtos.*
data class RegisterPushTokenRequestDTO(
    val pushToken: String,
) : DTORequest()

