// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.notifications
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*
data class RegisterPushTokenRequestDTO(
    val pushToken: String,
) : DTORequest()

