// AUTOGENERATED FILE. DO NOT EDIT.
package com.myapp.features.notifications
import com.myapp.common.base.*
import com.myapp.common.dtos.*
import io.ktor.server.application.*
import io.ktor.server.routing.*
import io.ktor.server.request.*
import io.ktor.server.response.*

interface NotificationsService {
    suspend fun RegisterPushToken(body: RegisterPushTokenRequestDTO): DTOResponse<Void>
    suspend fun UnregisterPushToken(body: EmptyRequestDTO): DTOResponse<Void>
}

fun Route.notificationsRoutes(service: NotificationsService) {
    post("/devices/push-token") {
        val body = call.receive<RegisterPushTokenRequestDTO>()
        call.respond(service.RegisterPushToken(body))
    }
    delete("/devices/push-token") {
        val body = call.receive<EmptyRequestDTO>()
        call.respond(service.UnregisterPushToken(body))
    }
}