/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.quizbackend.contracts.features.notifications

import com.quizbackend.contracts.common.base.*

interface NotificationsService {
    suspend fun RegisterPushToken(body: RegisterPushTokenRequestDTO): DTOResponse<GenericResponse>
    suspend fun UnregisterPushToken(body: EmptyRequestDTO): DTOResponse<GenericResponse>
}
