// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.notifications
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*
import io.ktor.server.application.*
import io.ktor.server.routing.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.auth.*

interface NotificationsService {
    suspend fun RegisterPushToken(body: RegisterPushTokenRequestDTO, userId: Int, token: String): DTOResponse<Void>
    suspend fun UnregisterPushToken(body: EmptyRequestDTO, token: String): DTOResponse<Void>
}

fun Route.notificationsRoutes(service: NotificationsService) {
    post("/devices/push-token") {
        val body = call.receive<RegisterPushTokenRequestDTO>()
        val userId = call.principal<UserIdPrincipal>()?.name?.toIntOrNull() ?: 0
        val token = call.request.headers["Authorization"]?.removePrefix("Bearer ")?.trim() ?: ""
        call.respond(service.RegisterPushToken(body, userId, token))
    }
    delete("/devices/push-token") {
        val body = call.receive<EmptyRequestDTO>()
        val token = call.request.headers["Authorization"]?.removePrefix("Bearer ")?.trim() ?: ""
        call.respond(service.UnregisterPushToken(body, token))
    }
}
