/**
 * AUTOGENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
 * This file was generated by the OpenAPI Generator tool.
 */
package com.example.features.notifications

import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.auth.*
import com.example.common.*

fun Route.notificationsRoutes() {
    route("") {
        post("/devices/push-token") {

            val requestBody = try {
                call.receive<RegisterPushTokenRequestDTO>()
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, "Serialization Error: ${e.localizedMessage}")
                return@post
            }
            // TODO: Implement logic for RegisterPushToken
            // val response: GenericResponse = service.doSomething(requestBody)
            call.respond(HttpStatusCode.NotImplemented, "Endpoint RegisterPushToken not implemented yet.")
        }

        delete("/devices/push-token") {
            // TODO: Implement logic for UnregisterPushToken
            // val response: GenericResponse = service.doSomething(requestBody)
            call.respond(HttpStatusCode.NotImplemented, "Endpoint UnregisterPushToken not implemented yet.")
        }
    }
}