// AUTOGENERATED FILE. DO NOT EDIT.
package com.quizbackend.contracts.features.notifications
import com.quizbackend.contracts.common.base.*
import com.quizbackend.contracts.common.dtos.*
import io.ktor.server.application.*
import io.ktor.server.auth.*
import io.ktor.server.routing.*
import io.ktor.server.request.*
import io.ktor.server.response.*

interface NotificationsService {
    suspend fun RegisterPushToken(body: RegisterPushTokenRequestDTO): DTOResponse<Unit>
    suspend fun UnregisterPushToken(body: EmptyRequestDTO): DTOResponse<Unit>
}

fun Route.notificationsRoutes(service: NotificationsService) {
    authenticate("auth-bearer") {
        post("/devices/push-token") {
            val body = call.receive<RegisterPushTokenRequestDTO>()
            call.respond(service.RegisterPushToken(body))
        }
        delete("/devices/push-token") {
            val body = call.receive<EmptyRequestDTO>()
            call.respond(service.UnregisterPushToken(body))
        }
    }
}